- name: log in Vault
  shell: '{{ vault_folder }}/approle-login.sh'
  register: approle_token

- name: fetch invalid TLS certificates
  uri:
    url: '{{ vault_url }}/v1/secret/data/mks/tls'
    method: GET
    status_code: 200
    body_format: json
    headers:
      X-Vault-Token: '{{ approle_token.stdout }}'
  register: tls_response
  no_log: true
  
- name: create a keys folder to save invalid certificates
  file:
    path: '/etc/ssl/cert/invalid-cert.mekomsolutions.net'
    state: directory

- name: parse invalid TLS certificates
  set_fact:
    intermediate_ca: '{{ tls_response.json.data.data[vault_intermediate_key_name] }}'
    certificate: '{{ tls_response.json.data.data[vault_certificate_key_name] }}'
    private_key: '{{ tls_response.json.data.data[vault_privatekey_key_name] }}'
  no_log: true

- name: save Let's Encrypt invalid ca
  copy:
    content: '{{ intermediate_ca }}'
    dest: '/etc/ssl/cert/invalid-cert.mekomsolutions.net/chain.pem'
  no_log: true

- name: save Let's Encrypt invalid certificates
  copy:
    content: '{{ certificate }}'
    dest: '/etc/ssl/cert/invalid-cert.mekomsolutions.net/cert.pem'
  no_log: true

- name: save Let's Encrypt invalid private key
  copy:
    content: '{{ private_key }}'
    dest: '/etc/ssl/cert/invalid-cert.mekomsolutions.net/privkey.pem'
    mode: 0400
  no_log: true

- name: create a folder to create symlink for apache's TLS keys
  file:
    path: '{{ tls_keys_folder }}/'
    state: directory

- name: create symlink to provide temporary certificates (invalid-cert.mekomsolutions.net)
  file:
    src: "{{ invalid_tls_keys_folder }}/cert.pem"
    dest: "{{ tls_keys_folder }}/cert.pem"
    state: link
    force: yes
  
- name: create symlink to provide temporary certificates (invalid-cert.mekomsolutions.net)
  file:
    src: "{{ invalid_tls_keys_folder }}/chain.pem"
    dest: "{{ tls_keys_folder }}/chain.pem"
    state: link
    force: yes
  
- name: create symlink to provide temporary certificates (invalid-cert.mekomsolutions.net)
  file:
    src: "{{ invalid_tls_keys_folder }}/privkey.pem"
    dest: "{{ tls_keys_folder }}/privkey.pem"
    state: link
    force: yes