---
- name: retrieve vars from configuration service
  hosts: localhost
  roles:
    - role: fetch_configs
  tags: fetch_configs

- hosts: all
  tasks:
    - name: set Vault URL
      set_fact:
        vault_url: "{{ hostvars['localhost']['vault_url'].stdout }}"
  tags: fetch_configs

- hosts: docker_host
  become: true
  roles:
   - role: common
   - role: vault
   - role: vpn
     conf_template: "{{ hostvars['localhost']['openvpn_client_conf_template'] }}"
   - role: geerlingguy.docker
     docker_users:
      - '{{ ansible_user }}'

- hosts: openmrs_cd_host
  become: true
  roles:
   - role: common
   - role: vault
   - role: vpn
     conf_template: "{{ hostvars['localhost']['openvpn_client_conf_template'] }}"
   - role: geerlingguy.docker
     docker_users:
      - '{{ ansible_user }}'
   - role: geerlingguy.pip
   - role: openmrs_cd
     nexus_repo_id: "{{ hostvars['localhost']['nexus_repo_id'].stdout }}"
     nexus_url: "{{ hostvars['localhost']['nexus_url'].stdout }}"
   - role: tls
   - role: geerlingguy.apache