---
- name: retrieve vars from configuration service
  hosts: localhost
  roles:
    - role: fetch_configs
  tags: fetch_configs

- name: bootstrap a testing infrastructure
  hosts: localhost
  roles:
    - role: terraform
      state: present
      action: initialize
  tags:
    - create_servers
    - terraform

- hosts: all
  tasks:
    - fail:
        msg: "Run this playbook with CentOS 7"
      when: ansible_distribution != 'CentOS' and ansible_distribution_major_version != '7'

- hosts: all
  tasks:
    - name: set Vault URL for all hosts
      set_fact:
        vault_url: "{{ hostvars['localhost']['vault_url'].stdout }}"
  tags: fetch_configs

- hosts: common
  become: true
  roles:
    - role: common
    - role: vault
    - role: vpn
      conf_template: "{{ hostvars['localhost']['openvpn_client_conf_template'] }}"
    - role: geerlingguy.docker
      docker_users:
      - '{{ ansible_user }}'
    - role: tls
    - role: letsencrypt
    - role: geerlingguy.apache

- hosts: docker_host
  become: true
  roles:
    - role: ssh

- hosts: openmrs_cd_host
  become: true
  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.nodejs
    - role: openmrs_cd
      nexus_repo_id: "{{ hostvars['localhost']['nexus_repo_id'].stdout }}"
      nexus_url: "{{ hostvars['localhost']['nexus_url'].stdout }}"
    - role: ssh

- name: flush the testing infrastructure
  hosts: localhost
  roles:
    - role: terraform
      state: absent
      action: destroy
  tags:
    - destroy_servers
    - terraform