---
vault_role: openmrs_cd
openmrs_cd_folder: /opt/openmrs-cd
openmrs_cd_repo_user: mekomsolutions
openmrs_cd_git_version: master
openmrs_cd_image: openmrscd
openmrs_cd_image_tag: latest
openmrs_cd_port: 8132 # Due to a SELinux policy that already uses 8080 by default, use 8100-8999 port

# Default vars that must be overridden in the inventory file, by server:
ansible_user: centos
common_name: openmrscd-host.vpn.mekomsolutions.net

# geerlingguy.apache role variables
apache_vhosts_filename: "openmrscd.conf"
apache_vhosts:
  - servername: "http"
    extra_parameters: |
      RewriteEngine On
      RewriteCond %{SERVER_PORT} !^443$
      RewriteRule ^/(.*) https://%{HTTP_HOST}/$1 [R,L]    

apache_allow_override: "All"
apache_options: "-Indexes +FollowSymLinks"

apache_vhosts_ssl: 
  - servername: "test.mekomsolutions.net"
    serveralias: "server.test"

    certificate_file: "{{ tls_keys_folder }}/cert.pem"
    certificate_key_file: "{{ tls_keys_folder }}/privkey.pem"
    certificate_chain_file: "{{ tls_keys_folder }}/chain.pem"

    proxy_pass: '/ http://localhost:{{ openmrs_cd_port }}/ nocanon'
    proxy_pass_reverse: '/ http://localhost:{{ openmrs_cd_port }}/'
    proxy_requests: "Off"
    proxy: 'http://localhost:{{ openmrs_cd_port }}/'
    order: 'deny,allow'
    allow: 'from all'

# Only used on Debian/Ubuntu
apache_mods_enabled:
  - rewrite.load
  - ssl.load
  - proxy_http.load

# Variables for pip packages
pip_install_packages: 
  - docker-py

nodejs_version: "8.x"

# SSH role vars
ssh_key_path: /opt/openmrs-cd/jenkins_home/.ssh
ssh_type: client

# Variables for Let's Encrypt
acme_api: 'https://acme-v02.api.letsencrypt.org/directory'
domain_name: prod.mekomsolutions.net