---
- name: install Git package
  package:
    name: git
    state: latest

- name: clone the OpenMRS CD GitHub repository
  git: 
    repo: 'https://github.com/mekomsolutions/openmrs-cd'
    dest: '{{ openmrs_cd_folder }}'
    version: master

- name: log in Vault
  shell: '{{ vault_folder }}/approle-login.sh'
  register: approle_token

- name: run the Docker OpenMRS CD Docker container
  docker:
    name: openmrscd
    ports:
      - "8080:8080"
    volumes:
      - "{{ openmrs_cd_folder }}/app:/opt/app"
      - "{{ openmrs_cd_folder }}/jenkins/jenkins_home:/var/jenkins_home"
    image: mekomsolutions/openmrscd:1.0.2-SNAPSHOT
