---
- name: configure/update packages
  package:
    name: '*'
    state: present
    update_cache: yes

- name: install Epel release
  include_role:
    name: geerlingguy.repo-epel
  when: ansible_os_family == 'RedHat'

- name: install 'nano' package
  package:
    name: nano
    state: present

- name: install 'tree' package
  package:
    name: tree
    state: present

- name: install 'jq' package
  package:
    name: jq
    state: present

- name: install 'git' package
  package:
    name: git
    state: present

- name: install 'bind-utils' package ('dig')
  package:
    name: bind-utils
    state: present
