---
- name: add Let's Encrypt repository
  git:
    repo: https://github.com/certbot/certbot
    dest: /opt/certbot/

- name: ensure log directory has been created
  file:
    path: '/var/log/letsencrypt/'
    state: directory

- name: install certbot
  command: /opt/certbot/certbot-auto --os-packages-only --non-interactive

- name: run certbot (This task may fail)
  command: /opt/certbot/certbot-auto --standalone --noninteractive --agree-tos --pre-hook "systemctl stop httpd.service" --post-hook "systemctl start httpd.service" --email {{ email }} --server {{ acme_api }} certonly -d {{ domain_name }}
  ignore_errors: yes

- name: add cron job to create or renew certificates
  cron:
    name: create_or_renew_certs
    minute: "50"
    hour: "5,23"
    user: root
    job: /opt/certbot/certbot-auto --standalone --noninteractive --agree-tos --pre-hook "systemctl stop httpd.service" --post-hook "systemctl start httpd.service" --post-hook "rsync -avL /etc/letsencrypt/live/{{ domain_name }}/ /etc/ssl/cert/{{ domain_name }}/" --email {{ email }} --server {{ acme_api }} certonly -d {{ domain_name }} &>> /var/log/letsencrypt/certbot.log