---
- name: add Let's Encrypt repository
  git:
    repo: https://github.com/certbot/certbot
    dest: /opt/certbot/

- name: ensure log directory has been created
  file:
    path: '/var/log/letsencrypt/'
    state: directory

- name: install certbot
  command: /opt/certbot/certbot-auto --os-packages-only --non-interactive

- name: run certbot (failure of this task will be ignored as it can be considered a normal behavior in some cases, eg, DNS mapping not yet available)
  shell: /opt/certbot/certbot-auto --standalone --noninteractive --agree-tos --pre-hook "systemctl stop httpd.service" --post-hook "systemctl start httpd.service" --deploy-hook "rsync -avL {{ le_tls_keys_folder }}/*.pem {{ domain_tls_keys_folder }}/" --email {{ email }} --server {{ acme_api }} certonly -d {{ domain_name }} &>> /var/log/letsencrypt/certbot.log
  ignore_errors: yes

- name: add cron job to create or renew certificates
  cron:
    name: create_or_renew_certs
    minute: "50"
    hour: "5,23"
    user: root
    job: /opt/certbot/certbot-auto --standalone --noninteractive --agree-tos --pre-hook "systemctl stop httpd.service" --post-hook "systemctl start httpd.service" --deploy-hook "rsync -avL {{ le_tls_keys_folder }}/*.pem {{ domain_tls_keys_folder }}/" --email {{ email }} --server {{ acme_api }} certonly -d {{ domain_name }} &>> /var/log/letsencrypt/certbot.log
